In [21]:
import numpy as np
import pandas as pd
import re 
from datetime import datetime
from pathlib import Path
from scipy.stats import linregress
from matplotlib import pyplot as plt
class Frontage:
    def __init__(self, input_file: str, assay_date: datetime):
        self.input_file = input_file
        self.filename = Path(input_file).parts[-1]
        assert self.filename.endswith(".xlsx"), "Incoming data must be an Excel file"
        self.assay_date = assay_date
    
    def __repr__(self):
        return f"Frontage assay handler built on file: '{self.filename}' on day: {self.assay_date}"

class FrontageStability(Frontage):
    def __init__(self, input_file, assay_date):
        super().__init__(input_file, assay_date)
        self.scraped_data = None 

        self.excel_file = pd.ExcelFile(input_file)
        self.sheet_names = self.excel_file.sheet_names
        
        self.target_sheet = self.check_sheet_names()

        self.data = self.read_data()
        self.check_columns()
        self.handle_outliers()
        self.scraped_data_transformation()
        self.calculate_remaining()
        self.calculate_regression()
        self.rationalize_half_life()
    
    def __repr__(self):
        return super().__repr__()
    
    def read_data(self):
        """Read in data and store."""
        df = pd.read_excel(self.input_file, sheet_name=self.target_sheet, usecols=range(22))
        df.columns = [c.lower().replace(" ", "_") for c in df.columns]
        df = df.loc[~(df.isna().all(axis=1))]
        return df

    def check_sheet_names(self):
        """Make sure there is a sheet name titled 'Raw' within the file."""

        # looking for any sheet resembling "raw data"
        for sheet in self.sheet_names:
            if re.search(r"[Rr]+aw", sheet):
                print(f"Valid sheet name '{sheet}' identified!")
                return sheet
        raise ValueError("Looking for sheet named 'Raw' but none found")
    
    def check_columns(self):
        """Change column headers and check to see if mandatory columns are present."""
        df = self.data.copy()
        
        # look for column names
        #TODO: these columns are those used in the first data delivery - do they change?
        mandatory_columns = ["cmpd_id", "sample_id", "is_area", "peak_area", "matrix", "notes"]
        for m in mandatory_columns:
            if m not in df.columns:
                raise ValueError(f"Column '{m}' not found in data sheet.")
            
        print("All needed column names found!")
        self.scraped_data = df[mandatory_columns]
            
        return 
    
    def handle_outliers(self):
        """Dictate whether data is outlier based on CRO recommendation."""
        df = self.scraped_data.copy()
        
        # fill empty string
        df.loc[:, "notes"] = df.notes.fillna("")

        # set new column with values
        df.loc[(df.notes.str.contains(r"[Oo]mitted", regex=True)), "outlier"] = True 
        df.loc[:, "outlier"] = df.outlier.fillna(False)

        # drop notes column, not needed
        df = df.drop("notes", axis=1)
        self.scraped_data = df
    
    def scraped_data_transformation(self):
        """Rename scraped data columns, transform data to prepare for calculations."""
        df = self.scraped_data.copy()

        # rename columns to resemble those used in CDD
        df = df.rename(columns=dict(
            zip(
                ["cmpd_id", "sample_id", "is_area", "peak_area"],
                ["molecule_name", "time", "is_area", "cmpd_area"]
            )
        ))
        
        # log10 transform values
        for column in ["is_area", "cmpd_area"]:
            component, suffix = column.split("_")
            df.loc[:, f"{component}_log10_{suffix}"] = np.log10(df[column])
        
        self.scraped_data = df 
        return 
    
    def calculate_remaining(self):
        """Calculate percent remaining and apply natural log to data."""
        df = self.scraped_data.copy()

        

        df = df.set_index(["molecule_name", "matrix", "time"]).sort_index()
        df = df.reset_index("time")

        # calculate is/cmpd ratio
        df.loc[:, "area_ratio"] = df.cmpd_area / df.is_area

        # for each molecule, use ratio to determine percent remaining
        for mol in df.index.unique():

            data = df.loc[mol, :]
            
            ref_val = data[data.time==0].area_ratio
            percent_remaining = data.area_ratio / ref_val
            
            # transform values using the natural log
            ln_percent_remaining = np.log(percent_remaining)


            # insert into dataframe
            df.loc[mol, "percent_remaining"] = percent_remaining
            df.loc[mol, "ln_percent_remaining"] = ln_percent_remaining
            
        self.scraped_data = df.reset_index()
        
        return 
    
    def calculate_regression(self):
        """Grab time and natural log data, filter, and perform linear regression."""

        df = self.scraped_data.copy()
        df = df.set_index(["molecule_name", "matrix"]).sort_index()

        for mol in df.index.unique():

            data = df.loc[mol, :]
            data = data[data.outlier==False]
            x, y = data.time.to_numpy(), data.ln_percent_remaining.to_numpy()


            m, b, r, _, _ = linregress(x, y)
            m, b, r = np.round(np.array([m, b, r]), 4)
            
            df.loc[mol, "rate_constant"] = m
            df.loc[mol, "linear_fit"] = -r
            df.loc[mol, "half_life"] = np.round(-0.693/m, 1)

        self.scraped_data = df.reset_index()
        
    def rationalize_half_life(self):
        """If half-life is longer than assay time, correct the values."""

        df = self.scraped_data.copy()
        max_time = df.time.max()

        df.loc[(df.half_life>max_time) | (df.half_life<0), "rational_half_life"] = max_time
        df.loc[:, "rational_half_life"] = df.rational_half_life.fillna(df.half_life)

        self.scraped_data = df

In [22]:
file = '/Users/delafield/Library/CloudStorage/GoogleDrive-delafield@calicolabs.com/My Drive/Projects/ADME_CRO/2025-11-10 Calico Liver Microsome Stability Result.xlsx'
file = '/Users/delafield/Library/CloudStorage/GoogleDrive-delafield@calicolabs.com/My Drive/Projects/ADME_CRO/2025-11-11 Calico Plasma Stability Result v2.xlsx'
file = '/Users/delafield/Library/CloudStorage/GoogleDrive-delafield@calicolabs.com/My Drive/Projects/ADME_CRO/2025-11-11 Calico SIF-SGF Stability Result v2.xlsx'
assay_date = datetime(2025, 11, 11)
fs = FrontageStability(file, assay_date)
fs.scraped_data.reset_index()[["molecule_name", "matrix", "rate_constant", "rational_half_life"]].groupby(["matrix", "molecule_name"]).mean()

Valid sheet name 'Raw Data' identified!
All needed column names found!

/var/folders/wc/8zzbrm9s0g3dm6svj8ztxlhr0000gp/T/ipykernel_54351/1479762598.py:81: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.loc[:, "outlier"] = df.outlier.fillna(False)

                                   rate_constant  rational_half_life
matrix              molecule_name
FasSGF + Pepsin     CP-5a-1174           -0.0002               240.0
                    CP-5a-1193           -0.0001               240.0
                    CP-5a-1262           -0.0011               240.0
                    CP-5a-470             0.0002               240.0
                    CP-5a-838             0.0002               240.0
                    CP-5a-841             0.0003               240.0
                    CP-5a-850            -0.0003               240.0
                    Somatostatin         -0.0113                61.3
FasSIF + Pancreatin BAN                  -0.1210                 5.7
                    CP-5a-1174           -0.1665                 4.2
                    CP-5a-1193           -0.1671                 4.1
                    CP-5a-1262           -0.1106                 6.3
                    CP-5a-470            -0.2541                 2.7
                    CP-5a-838            -0.0050               138.6
                    CP-5a-841            -0.0359                19.3
                    CP-5a-850            -0.0005               240.0

In [28]:
fs.scraped_data.molecule_name.unique().tolist()
mol_map = {'CP-5a-1174': 'CAL-0011526',
'CP-5a-1193': 'CAL-0011553',
'CP-5a-1262': 'CAL-0011599',
'CP-5a-470': 'CAL-0010270',
'CP-5a-838': 'CAL-0010995',
'CP-5a-841': 'CAL-0010971',
'CP-5a-850': 'CAL-0010967',
'CP-8-176': 'CAL-0012008',
'CP-8-178': 'CAL-0012010',
'CP-5a-1174': 'CAL-0011526', 
'CP-5a-1193': 'CAL-0011553', 
'CP-5a-1262': 'CAL-0011599', 
'CP-5a-470': 'CAL-0010270', 
'CP-5a-838': 'CAL-0010995', 
'CP-5a-841': 'CAL-0010971', 
'CP-5a-850': 'CAL-0010967', 
'CP-8-176': 'CAL-0012008', 
'CP-8-178': 'CAL-0012010'}

data = fs.scraped_data.copy()
data.loc[:, "mapped_name"] = data.molecule_name.map(mol_map)
data.loc[:, "batch"] = 1
data = data.loc[~(data.mapped_name.isna()), :]
data
# data.to_csv('/Users/delafield/Library/CloudStorage/GoogleDrive-delafield@calicolabs.com/My Drive/Projects/ADME_CRO/20251111_PlasmaStability.csv', index=False)

,molecule_name,matrix,time,is_area,cmpd_area,outlier,is_log10_area,cmpd_log10_area,area_ratio,percent_remaining,ln_percent_remaining,rate_constant,linear_fit,half_life,rational_half_life,mapped_name,batch
4,CP-5a-1174,FasSGF + Pepsin,0.0,145286.88,62542.71,False,5.162226,4.796177,0.430477,1.000000,0.000000,-0.0002,0.2411,3465.0,240.0,CAL-0011526,1
5,CP-5a-1174,FasSGF + Pepsin,30.0,152787.38,65283.76,False,5.184087,4.814805,0.427285,0.992584,-0.007443,-0.0002,0.2411,3465.0,240.0,CAL-0011526,1
6,CP-5a-1174,FasSGF + Pepsin,60.0,152215.01,53306.25,False,5.182457,4.726778,0.350204,0.813524,-0.206380,-0.0002,0.2411,3465.0,240.0,CAL-0011526,1
7,CP-5a-1174,FasSGF + Pepsin,240.0,143542.95,57078.91,False,5.156982,4.756476,0.397643,0.923727,-0.079339,-0.0002,0.2411,3465.0,240.0,CAL-0011526,1
8,CP-5a-1174,FasSIF + Pancreatin,0.0,151142.85,39642.33,False,5.179388,4.598159,0.262284,1.000000,0.000000,-0.1665,1.0000,4.2,4.2,CAL-0011526,1
9,CP-5a-1174,FasSIF + Pancreatin,30.0,142354.02,253.01,False,5.153370,2.403138,0.001777,0.006776,-4.994315,-0.1665,1.0000,4.2,4.2,CAL-0011526,1
10,CP-5a-1174,FasSIF + Pancreatin,60.0,161370.58,269.01,True,5.207824,2.429768,0.001667,0.006356,-5.058382,-0.1665,1.0000,4.2,4.2,CAL-0011526,1
11,CP-5a-1174,FasSIF + Pancreatin,240.0,122251.92,98.38,True,5.087256,1.992907,0.000805,0.003068,-5.786674,-0.1665,1.0000,4.2,4.2,CAL-0011526,1
12,CP-5a-1193,FasSGF + Pepsin,0.0,151812.81,61956.94,False,5.181308,4.792090,0.408114,1.000000,0.000000,-0.0001,0.1932,6930.0,240.0,CAL-0011553,1
13,CP-5a-1193,FasSGF + Pepsin,30.0,142246.29,68388.82,False,5.153041,4.834985,0.480778,1.178047,0.163858,-0.0001,0.1932,6930.0,240.0,CAL-0011553,1
14,CP-5a-1193,FasSGF + Pepsin,60.0,132280.86,62919.40,False,5.121497,4.798785,0.475650,1.165483,0.153136,-0.0001,0.1932,6930.0,240.0,CAL-0011553,1
15,CP-5a-1193,FasSGF + Pepsin,240.0,132814.06,56664.22,False,5.123244,4.753309,0.426643,1.045402,0.044401,-0.0001,0.1932,6930.0,240.0,CAL-0011553,1
16,CP-5a-1193,FasSIF + Pancreatin,0.0,147977.15,54770.31,False,5.170195,4.738545,0.370127,1.000000,0.000000,-0.1671,1.0000,4.1,4.1,CAL-0011553,1
17,CP-5a-1193,FasSIF + Pancreatin,30.0,153399.18,377.45,False,5.185823,2.576859,0.002461,0.006648,-5.013451,-0.1671,1.0000,4.1,4.1,CAL-0011553,1
18,CP-5a-1193,FasSIF + Pancreatin,60.0,142593.96,470.93,True,5.154101,2.672956,0.003303,0.008923,-4.719137,-0.1671,1.0000,4.1,4.1,CAL-0011553,1
19,CP-5a-1193,FasSIF + Pancreatin,240.0,154220.28,314.35,True,5.188141,2.497413,0.002038,0.005507,-5.201721,-0.1671,1.0000,4.1,4.1,CAL-0011553,1
20,CP-5a-1262,FasSGF + Pepsin,0.0,135224.62,18741.03,False,5.131056,4.272793,0.138592,1.000000,0.000000,-0.0011,0.9899,630.0,240.0,CAL-0011599,1
21,CP-5a-1262,FasSGF + Pepsin,30.0,138361.47,17884.57,False,5.141015,4.252479,0.129260,0.932665,-0.069709,-0.0011,0.9899,630.0,240.0,CAL-0011599,1
22,CP-5a-1262,FasSGF + Pepsin,60.0,143213.17,18103.97,False,5.155983,4.257774,0.126413,0.912123,-0.091981,-0.0011,0.9899,630.0,240.0,CAL-0011599,1
23,CP-5a-1262,FasSGF + Pepsin,240.0,151190.64,15985.19,False,5.179525,4.203718,0.105729,0.762878,-0.270657,-0.0011,0.9899,630.0,240.0,CAL-0011599,1
24,CP-5a-1262,FasSIF + Pancreatin,0.0,139049.93,9904.90,False,5.143171,3.995850,0.071233,1.000000,0.000000,-0.1106,1.0000,6.3,6.3,CAL-0011599,1
25,CP-5a-1262,FasSIF + Pancreatin,30.0,144109.99,371.46,False,5.158694,2.569912,0.002578,0.036186,-3.319087,-0.1106,1.0000,6.3,6.3,CAL-0011599,1
26,CP-5a-1262,FasSIF + Pancreatin,60.0,135515.14,522.83,True,5.131988,2.718360,0.003858,0.054162,-2.915779,-0.1106,1.0000,6.3,6.3,CAL-0011599,1
27,CP-5a-1262,FasSIF + Pancreatin,240.0,120311.60,391.56,True,5.080308,2.592798,0.003255,0.045689,-3.085898,-0.1106,1.0000,6.3,6.3,CAL-0011599,1
28,CP-5a-470,FasSGF + Pepsin,0.0,145702.57,176823.39,False,5.163467,5.247540,1.213591,1.000000,0.000000,0.0002,-0.5934,-3465.0,240.0,CAL-0010270,1
29,CP-5a-470,FasSGF + Pepsin,30.0,136037.55,179835.98,False,5.133659,5.254877,1.321958,1.089294,0.085530,0.0002,-0.5934,-3465.0,240.0,CAL-0010270,1
30,CP-5a-470,FasSGF + Pepsin,60.0,140339.67,174045.93,False,5.147180,5.240664,1.240176,1.021906,0.021669,0.0002,-0.5934,-3465.0,240.0,CAL-0010270,1
31,CP-5a-470,FasSGF + Pepsin,240.0,138962.09,183625.42,False,5.142896,5.263933,1.321407,1.088840,0.085113,0.0002,-0.5934,-3465.0,240.0,CAL-0010270,1
32,CP-5a-470,FasSIF + Pancreatin,0.0,152652.49,96296.35,False,5.183704,4.983610,0.630821,1.000000,0.000000,-0.2541,1.0000,2.7,2.7,CAL-0010270,1
33,CP-5a-470,FasSIF + Pancreatin,30.0,145459.37,44.81,False,5.162742,1.651375,0.000308,0.000488,-7.624487,-0.2541,1.0000,2.7,2.7,CAL-0010270,1
34,CP-5a-470,FasSIF + Pancreatin,60.0,149121.10,96.79,True,5.173539,1.985830,0.000649,0.001029,-6.879237,-0.2541,1.0000,2.7,2.7,CAL-0010270,1
35,CP-5a-470,FasSIF + Pancreatin,240.0,152368.79,205.34,True,5.182896,2.312474,0.001348,0.002136,-6.148658,-0.2541,1.0000,2.7,2.7,CAL-0010270,1
36,CP-5a-838,FasSGF + Pepsin,0.0,142389.08,69210.86,False,5.153477,4.840174,0.486069,1.000000,0.000000,0.0002,-0.9125,-3465.0,240.0,CAL-0010995,1
37,CP-5a-838,FasSGF + Pepsin,30.0,154662.42,75546.98,False,5.189385,4.878217,0.488464,1.004928,0.004915,0.0002,-0.9125,-3465.0,240.0,CAL-0010995,1
38,CP-5a-838,FasSGF + Pepsin,60.0,141531.94,70780.54,False,5.150854,4.849914,0.500103,1.028873,0.028464,0.0002,-0.9125,-3465.0,240.0,CAL-0010995,1
39,CP-5a-838,FasSGF + Pepsin,240.0,144144.56,73309.47,False,5.158798,4.865160,0.508583,1.046319,0.045279,0.0002,-0.9125,-3465.0,240.0,CAL-0010995,1
40,CP-5a-838,FasSIF + Pancreatin,0.0,155403.49,74579.35,False,5.191461,4.872619,0.479908,1.000000,0.000000,-0.0050,0.9947,138.6,138.6,CAL-0010995,1
41,CP-5a-838,FasSIF + Pancreatin,30.0,156988.78,59287.03,False,5.195869,4.772960,0.377651,0.786925,-0.239623,-0.0050,0.9947,138.6,138.6,CAL-0010995,1
42,CP-5a-838,FasSIF + Pancreatin,60.0,150642.43,46990.10,False,5.177947,4.672006,0.311931,0.649982,-0.430811,-0.0050,0.9947,138.6,138.6,CAL-0010995,1
43,CP-5a-838,FasSIF + Pancreatin,240.0,146798.97,20201.92,False,5.166723,4.305393,0.137616,0.286756,-1.249125,-0.0050,0.9947,138.6,138.6,CAL-0010995,1
44,CP-5a-841,FasSGF + Pepsin,0.0,145447.63,85221.55,False,5.162707,4.930549,0.585926,1.000000,0.000000,0.0003,-0.6802,-2310.0,240.0,CAL-0010971,1
45,CP-5a-841,FasSGF + Pepsin,30.0,140790.34,77428.09,False,5.148573,4.888899,0.549953,0.938605,-0.063360,0.0003,-0.6802,-2310.0,240.0,CAL-0010971,1
46,CP-5a-841,FasSGF + Pepsin,60.0,152805.30,92022.43,False,5.184138,4.963894,0.602220,1.027809,0.027430,0.0003,-0.6802,-2310.0,240.0,CAL-0010971,1
47,CP-5a-841,FasSGF + Pepsin,240.0,144712.05,89350.22,False,5.160505,4.951096,0.617435,1.053776,0.052380,0.0003,-0.6802,-2310.0,240.0,CAL-0010971,1
48,CP-5a-841,FasSIF + Pancreatin,0.0,151454.55,74673.31,False,5.180282,4.873165,0.493041,1.000000,0.000000,-0.0359,0.9936,19.3,19.3,CAL-0010971,1
49,CP-5a-841,FasSIF + Pancreatin,30.0,152997.07,20774.13,False,5.184683,4.317523,0.135781,0.275395,-1.289547,-0.0359,0.9936,19.3,19.3,CAL-0010971,1
50,CP-5a-841,FasSIF + Pancreatin,60.0,152756.06,8719.59,False,5.183998,3.940496,0.057082,0.115775,-2.156107,-0.0359,0.9936,19.3,19.3,CAL-0010971,1
51,CP-5a-841,FasSIF + Pancreatin,240.0,144971.44,696.89,True,5.161282,2.843164,0.004807,0.009750,-4.630502,-0.0359,0.9936,19.3,19.3,CAL-0010971,1
52,CP-5a-850,FasSGF + Pepsin,0.0,126078.85,40792.76,False,5.100642,4.610583,0.323550,1.000000,0.000000,-0.0003,0.4322,2310.0,240.0,CAL-0010967,1
53,CP-5a-850,FasSGF + Pepsin,30.0,120470.27,43398.42,False,5.080880,4.637474,0.360242,1.113405,0.107423,-0.0003,0.4322,2310.0,240.0,CAL-0010967,1
54,CP-5a-850,FasSGF + Pepsin,60.0,126147.36,37177.01,False,5.100878,4.570274,0.294711,0.910868,-0.093357,-0.0003,0.4322,2310.0,240.0,CAL-0010967,1
55,CP-5a-850,FasSGF + Pepsin,240.0,128533.08,39360.78,False,5.109015,4.595064,0.306231,0.946472,-0.055014,-0.0003,0.4322,2310.0,240.0,CAL-0010967,1
56,CP-5a-850,FasSIF + Pancreatin,0.0,134730.49,31218.13,False,5.129466,4.494407,0.231708,1.000000,0.000000,-0.0005,0.9967,1386.0,240.0,CAL-0010967,1
57,CP-5a-850,FasSIF + Pancreatin,30.0,126635.48,28763.79,False,5.102555,4.458846,0.227138,0.980279,-0.019918,-0.0005,0.9967,1386.0,240.0,CAL-0010967,1
58,CP-5a-850,FasSIF + Pancreatin,60.0,129017.11,28603.90,False,5.110647,4.456425,0.221706,0.956835,-0.044125,-0.0005,0.9967,1386.0,240.0,CAL-0010967,1
59,CP-5a-850,FasSIF + Pancreatin,240.0,136189.43,27594.23,False,5.134143,4.440818,0.202617,0.874448,-0.134163,-0.0005,0.9967,1386.0,240.0,CAL-0010967,1

In [76]:
import matplotlib.pyplot as plt

In [87]:
d = fs.scraped_data.set_index(["molecule_name", "time"]).sort_index()
d = d.reset_index("time")
# display(d)

l = []

for idx in d.index.unique():
    data = d.loc[idx, :]
    x, y = data.time.to_numpy(), data.ln_percent_remaining.to_numpy()
    print(x)
    print(y)
    # display(data)
    m, b, r, _, _ = linregress(x, y)
    # plt.scatter(data.time, data.ln_percent_remaining)
    # plt.plot(np.linspace(0, 60, 100), np.linspace(0, 60, 100)*m + b)
    # l.append(idx)
    print(linregress(data.time.to_numpy(), data.ln_percent_remaining.to_numpy()))
    # break
    d.loc[idx, "regression_slope"] = m 
    d.loc[idx, "half_life"] = -0.693/m 

# plt.legend(l)
d

[ 0. 15. 30. 60.]
[ 0.         -0.03575245 -0.24760979 -0.65303794]
LinregressResult(slope=-0.011462274053825423, intercept=0.06678464796459854, rvalue=-0.9790752494175289, pvalue=0.020924750582471112, stderr=0.0016846163711640959, intercept_stderr=0.057899115283659694)
[ 0. 15. 30. 60.]
[ 0.         -0.03715852 -0.26693563 -0.47745461]
LinregressResult(slope=-0.008481050497909877, intercept=0.027240384910891507, rvalue=-0.9785209750215745, pvalue=0.021479024978425465, stderr=0.0012634036369990837, intercept_stderr=0.04342232099873109)
[ 0. 15. 30. 60.]
[ 0.         -2.70934344 -4.49691586 -4.33998354]
LinregressResult(slope=-0.0674833093654895, intercept=-1.115123840305996, rvalue=-0.8282570791014612, pvalue=0.1717429208985388, stderr=0.03228302869207879, intercept_stderr=1.109545669829117)
[ 0. 15. 30. 60.]
[ 0.         -0.04706965 -0.04014568 -0.24903714]
LinregressResult(slope=-0.004076706695791768, intercept=0.022950433924405655, rvalue=-0.933092423276033, pvalue=0.06690757672396698, stderr=0.0011110504140909023, intercept_stderr=0.03818604467612693)
[ 0. 15. 30. 60.]
[ 0.         -0.08675127 -0.06078718 -0.05857297]
LinregressResult(slope=-0.0006241716061977982, intercept=-0.035143351231319425, rvalue=-0.4361976506731855, pvalue=0.5638023493268145, stderr=0.0009104922115599917, intercept_stderr=0.031292996093560566)
[ 0. 15. 30. 60.]
[ 0.         -0.11996287 -0.27633694 -0.84915968]
LinregressResult(slope=-0.01439787709304967, intercept=0.06657940018241376, rvalue=-0.98105624527307, pvalue=0.018943754726929992, stderr=0.0020103468387791083, intercept_stderr=0.06909424921365337)
[ 0. 15. 30. 60.]
[ 0.         -0.18449936 -0.37049834 -0.88427262]
LinregressResult(slope=-0.014810388213695994, intercept=0.028955108961385922, rvalue=-0.9959357326334097, pvalue=0.0040642673665902684, stderr=0.0009470753691096768, intercept_stderr=0.03255033425830002)
[ 0. 15. 30. 60.]
[ 0.         -0.01482713 -0.22636634 -0.23047577]
LinregressResult(slope=-0.0042974606612398505, intercept=-0.005108967565950057, rvalue=-0.8617367778567917, pvalue=0.1382632221432083, stderr=0.0017891005920800394, intercept_stderr=0.06149016666822819)
[ 0. 15. 30. 60.]
[ 0.         -0.00334799  0.01624616 -0.26832229]
LinregressResult(slope=-0.0045497342600718735, intercept=0.05557449277693094, rvalue=-0.8533675963644599, pvalue=0.14663240363554006, stderr=0.0019653081043231667, intercept_stderr=0.0675462986397831)
[ 0. 15. 30. 60.]
[ 0.         -0.69802237 -1.31456093 -3.6752482 ]
LinregressResult(slope=-0.06151948117135042, intercept=0.19292850343432688, rvalue=-0.9878848479577886, pvalue=0.01211515204221136, stderr=0.006833628858463683, intercept_stderr=0.23486716136358374)

,time,is_area,cmpd_area,is_log10_area,cmpd_log10_area,area_ratio,percent_remaining,ln_percent_remaining,regression_slope,half_life
molecule_name,,,,,,,,,,
CP-5a-1174,0.0,148848.17,25364.59,5.172743,4.404228,0.170406,1.000000,0.000000,-0.011462,60.459207
CP-5a-1174,15.0,140952.93,23175.62,5.149074,4.365031,0.164421,0.964879,-0.035752,-0.011462,60.459207
CP-5a-1174,30.0,143289.45,19061.76,5.156214,4.280163,0.133030,0.780665,-0.247610,-0.011462,60.459207
CP-5a-1174,60.0,151541.25,13440.16,5.180531,4.128404,0.088690,0.520462,-0.653038,-0.011462,60.459207
CP-5a-1193,0.0,146539.91,59297.29,5.165956,4.773035,0.404649,1.000000,0.000000,-0.008481,81.711576
CP-5a-1193,15.0,142591.21,55594.77,5.154093,4.745034,0.389889,0.963523,-0.037159,-0.008481,81.711576
CP-5a-1193,30.0,134054.96,41536.81,5.127283,4.618433,0.309849,0.765722,-0.266936,-0.008481,81.711576
CP-5a-1193,60.0,143945.57,36134.44,5.158198,4.557921,0.251028,0.620360,-0.477455,-0.008481,81.711576
CP-5a-1262,0.0,136765.55,6576.38,5.135977,3.817987,0.048085,1.000000,0.000000,-0.067483,10.269206
CP-5a-1262,15.0,139202.29,445.66,5.143646,2.649004,0.003202,0.066581,-2.709343,-0.067483,10.269206
CP-5a-1262,30.0,124891.10,66.92,5.096531,1.825556,0.000536,0.011143,-4.496916,-0.067483,10.269206
CP-5a-1262,60.0,132467.11,83.04,5.122108,1.919287,0.000627,0.013037,-4.339984,-0.067483,10.269206
CP-5a-470,0.0,140360.20,220456.77,5.147244,5.343323,1.570650,1.000000,0.000000,-0.004077,169.990154
CP-5a-470,15.0,152513.69,228531.57,5.183309,5.358946,1.498433,0.954021,-0.047070,-0.004077,169.990154
CP-5a-470,30.0,140645.51,212212.17,5.148126,5.326770,1.508844,0.960649,-0.040146,-0.004077,169.990154
CP-5a-470,60.0,433566.77,530859.99,5.637056,5.724980,1.224402,0.779551,-0.249037,-0.004077,169.990154
CP-5a-838,0.0,146163.96,71107.68,5.164840,4.851917,0.486493,1.000000,0.000000,-0.000624,1110.271587
CP-5a-838,15.0,162491.07,72481.99,5.210829,4.860230,0.446068,0.916905,-0.086751,-0.000624,1110.271587
CP-5a-838,30.0,148145.09,67820.96,5.170687,4.831364,0.457801,0.941023,-0.060787,-0.000624,1110.271587
CP-5a-838,60.0,310633.10,142523.35,5.492248,5.153886,0.458816,0.943109,-0.058573,-0.000624,1110.271587
CP-5a-841,0.0,151768.01,85819.10,5.181180,4.933584,0.565462,1.000000,0.000000,-0.014398,48.132096
CP-5a-841,15.0,143579.77,72010.82,5.157093,4.857398,0.501539,0.886953,-0.119963,-0.014398,48.132096
CP-5a-841,30.0,153202.41,65713.97,5.185266,4.817658,0.428936,0.758557,-0.276337,-0.014398,48.132096
CP-5a-841,60.0,141262.87,34170.11,5.150028,4.533646,0.241890,0.427774,-0.849160,-0.014398,48.132096
CP-5a-850,0.0,134232.09,31944.35,5.127856,4.504394,0.237978,1.000000,0.000000,-0.014810,46.791481
CP-5a-850,15.0,132292.06,26178.48,5.121534,4.417944,0.197884,0.831520,-0.184499,-0.014810,46.791481
CP-5a-850,30.0,128735.70,21151.02,5.109699,4.325331,0.164298,0.690390,-0.370498,-0.014810,46.791481
CP-5a-850,60.0,137518.34,13516.48,5.138361,4.130864,0.098289,0.413014,-0.884273,-0.014810,46.791481
CP-8-176,0.0,131818.35,297623.22,5.119976,5.473667,2.257828,1.000000,0.000000,-0.004297,161.258021
CP-8-176,15.0,132460.63,294671.69,5.122087,5.469338,2.224598,0.985282,-0.014827,-0.004297,161.258021
CP-8-176,30.0,133264.01,239935.31,5.124713,5.380094,1.800451,0.797426,-0.226366,-0.004297,161.258021
CP-8-176,60.0,136729.03,245164.35,5.135861,5.389457,1.793067,0.794156,-0.230476,-0.004297,161.258021
CP-8-178,0.0,134540.23,146947.75,5.128852,5.167163,1.092222,1.000000,0.000000,-0.004550,152.316588
CP-8-178,15.0,136263.45,148332.44,5.134379,5.171236,1.088571,0.996658,-0.003348,-0.004550,152.316588
CP-8-178,30.0,128274.33,142398.74,5.108140,5.153506,1.110111,1.016379,0.016246,-0.004550,152.316588
CP-8-178,60.0,136930.33,114361.42,5.136500,5.058280,0.835180,0.764661,-0.268322,-0.004550,152.316588
Propantheline,0.0,156212.03,5134322.76,5.193714,6.710483,32.867653,1.000000,0.000000,-0.061519,11.264724
Propantheline,15.0,155942.89,2550274.94,5.192966,6.406587,16.353903,0.497568,-0.698022,-0.061519,11.264724
Propantheline,30.0,157801.78,1393073.49,5.198112,6.143974,8.827996,0.268592,-1.314561,-0.061519,11.264724
Propantheline,60.0,145100.64,120864.29,5.161669,5.082298,0.832969,0.025343,-3.675248,-0.061519,11.264724